Fixed rsync command, added verbosity

diff --git a/speculo b/speculo
--- a/speculo
+++ b/speculo
@@ -1,14 +1,14 @@
 #!/bin/bash
 declare -A config #initialize associated array (keys can be anything)
 config=(
-    [dotdir]="~/dotfiles/"
+    [dotdir]="${HOME}/dotfiles/"
     [dotrc]="${config[dotdir]}/.bashrc"
     [soscheck]="1"
     [sonoclean]="0"
     [soconf]="~/speculo.conf"
 )
 
-HOSTNAME=${1}    
+SPEC_HOSTNAME=${1}    
 so_config_parse()
 {
     while read line
@@ -34,7 +34,7 @@ plzhlp()
 {
     cat <<EOF
     ${0} - Usage: 
-    ${0} [-h] HOSTNAME [-c config.file] [-d dotfiles_dir] [-r ./rc_file] [-no]
+    ${0} [-h] SPEC_HOSTNAME [-c config.file] [-d dotfiles_dir] [-r ./rc_file] [-no]
         -c      Specify a different config file.  default: ./speculo.conf
         
         -h      Specify Hostname. If -h isn't supplied the FIRST positional argument is used
@@ -57,7 +57,7 @@ do
         c)      ${config[soconf]}=${OPTARG}
                 so_config_parse
                 ;;
-        h)      HOSTNAME=${OPTARG}
+        h)      SPEC_HOSTNAME=${OPTARG}
                 ;;
         d)      ${config[dotdir]}=${OPTARG}
                 ;;
@@ -81,49 +81,50 @@ done
 
 parallel_lines()
 {
-    pgrep -a $0 -u ${USER} | grep ${HOSTNAME} | grep -qv $$
+    pgrep -a $0 -u ${USER} | grep ${SPEC_HOSTNAME} | grep -qv $$
 }
 
 
 rem_dotfiles()
 {
-    ssh ${HOSTNAME} -qt 'rm -r ${config[dotdir]}'
+        ssh ${SPEC_HOSTNAME} -qt 'rm -r ${config[dotdir]}'
 }
 
 rem_routine()
 {
-    if rem_dotfiles
-    then
-        echo "Files removed!"
-    elif rem_dotfiles
-    then
-        echo "Files removed after 2 tries."
-    else
-        echo "Could not remove dot files, please manually clean up"
-    fi
+        if rem_dotfiles
+        then
+            echo "Files removed!"
+        elif rem_dotfiles
+        then
+            echo "Files removed after 2 tries."
+        else
+            echo "Could not remove dot files, please manually clean up"
+        fi
 }
 
 spec_oscheck()
 {
-    # Exits 0 if system is Solaris, 1 if centos or oracle linux or 5 if other.
-    if ssh -q ${HOSTNAME}  'cat /etc/release 2>/dev/null | grep -qi 'solaris''
-    then
-    CORE_EXIT=0
-    elif ssh -q ${HOSTNAME} 'lsb_release -a' | grep -i 'Description' | grep -qEi 'centos|oracle linux'
-    then
-    CORE_EXIT=1
-    else
-    CORE_EXIT=5
-    fi
+        # Exits 0 if system is Solaris, 1 if centos or oracle linux or 5 if other.
+        if ssh -q ${SPEC_HOSTNAME}  'cat /etc/release 2>/dev/null | grep -qi 'solaris''
+        then
+        CORE_EXIT=0
+        elif ssh -q ${SPEC_HOSTNAME} 'lsb_release -a' | grep -i 'Description' | grep -qEi 'centos|oracle linux'
+        then
+        CORE_EXIT=1
+        else
+        CORE_EXIT=5
+        fi
 }
-
-
+spec_source="${config[dotdir]}"
+spec_DEST="${USER}_$(basename ${config[dotdir]})"
+### Rsync command 
 spec_the_thing()
 {
-    rsync -r ${config[dotdir]} ${HOSTNAME}:~/${USER}_${config[dotdir]} &&\
-    ssh ${HOSTNAME} -t "bash --rcfile ${config[dotrc]}" || echo -e "\e[31mFailed to SSH or Rsync to system!\e[m"
+    
+    rsync  -vv -r "${spec_source}" "${SPEC_HOSTNAME}":~/"${spec_DEST}"/ &&\
+    ssh ${SPEC_HOSTNAME} -t "bash --rcfile ${spec_DEST}${config[dotrc]}" || echo -e "\e[31mFailed to SSH or Rsync to system!\e[m"
 }
-
 
 if $(exit ${config[soscheck]})
 then 
@@ -132,7 +133,7 @@ then
     then
         
         echo "System is Solaris, default SSH used."
-        ssh ${HOSTNAME}
+        ssh ${SPEC_HOSTNAME}
    
     elif [[ CORE_EXIT == 1 ]]
     then    
@@ -145,13 +146,13 @@ then
             then
                 rem_routine
             else
-                echo "Still logged in to ${HOSTNAME} elsewhere using ${0}, please log out and/or clean up manually!"
+                echo "Still logged in to ${SPEC_HOSTNAME} elsewhere using ${0}, please log out and/or clean up manually!"
             fi    
         fi
 
     else
         echo "Unknown system, defualt SSH used."
-        ssh ${HOSTNAME}
+        ssh ${SPEC_HOSTNAME}
     fi
 else
     spec_the_thing &&\
@@ -162,7 +163,7 @@ else
         then
             rem_routine
         else
-            echo "Still logged in to ${HOSTNAME} elsewhere using ${0}, please log out and/or clean up manually!"
+            echo "Still logged in to ${SPEC_HOSTNAME} elsewhere using ${0}, please log out and/or clean up manually!"
         fi
     fi
 fi
